[package]
name = "ariel-os-atsamd"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ariel-os-embassy-common = { workspace = true }
ariel-os-log = { workspace = true }
ariel-os-random = { workspace = true, optional = true }
ariel-os-rt = { workspace = true, features = ["memory-x"] }
cortex-m = { workspace = true, optional = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true, optional = true }
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-cortex-m",
] }
embassy-sync = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-io-async = { workspace = true, optional = true }

atsamd-hal = { workspace = true, default-features = false, features = [
  "same54n",
]}

